version: "3"

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: webxdao-website
    restart: always
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - app-net
    volumes:
      - ./src:/app/src
      - /app/node_modules

networks:
  app-net:
    driver: bridge
