blank_issues_enabled: false
contact_links:
  - name: Our socials
    url: https://bio.link/web3community
    about: Feel free to contact us via your preferred platform.
  - name: Discord community
    url: https://discord.gg/TSRwqx4K2v
    about: Join our inclusive Discord community.
